"""Initial Sprint 3 schema

Revision ID: dd8b738b58d1
Revises:
Create Date: 2026-05-15 14:48:09.061145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8b738b58d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('underwriter', sa.String(length=255), nullable=True),
    sa.Column('offering_price_range', sa.String(length=100), nullable=True),
    sa.Column('total_shares', sa.BigInteger(), nullable=True),
    sa.Column('acquirer', sa.String(length=255), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('fair_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pe_multiple', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb_multiple', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('premium_1d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pre_event_insider_volume', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('pre_event_smart_money_score', sa.Integer(), nullable=True),
    sa.Column('acquirer_entity_id', sa.Integer(), nullable=True),
    sa.Column('target_entity_id', sa.Integer(), nullable=True),
    sa.Column('post_event_absorption_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('event_version', sa.Integer(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('state_transition_log', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rationale_ai', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acquirer_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash')
    )
    op.create_index(op.f('ix_corporate_events_event_type'), 'corporate_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_corporate_events_id'), 'corporate_events', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_events_ticker'), 'corporate_events', ['ticker'], unique=False)
    op.create_table('event_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_snapshot', sa.Text(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['corporate_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_snapshots_id'), 'event_snapshots', ['id'], unique=False)
    op.add_column('stocks', sa.Column('trailing_pe', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('stocks', sa.Column('price_to_book', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('stocks', sa.Column('fifty_two_week_high', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('stocks', sa.Column('fifty_two_week_low', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('stocks', sa.Column('avg_volume', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'avg_volume')
    op.drop_column('stocks', 'fifty_two_week_low')
    op.drop_column('stocks', 'fifty_two_week_high')
    op.drop_column('stocks', 'price_to_book')
    op.drop_column('stocks', 'trailing_pe')
    op.drop_index(op.f('ix_event_snapshots_id'), table_name='event_snapshots')
    op.drop_table('event_snapshots')
    op.drop_index(op.f('ix_corporate_events_ticker'), table_name='corporate_events')
    op.drop_index(op.f('ix_corporate_events_id'), table_name='corporate_events')
    op.drop_index(op.f('ix_corporate_events_event_type'), table_name='corporate_events')
    op.drop_table('corporate_events')
    # ### end Alembic commands ###
